baseurl: https://example.com
title: Sam's Site
author: Nan Xiao
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
  progressively: no
  sitename: Sam's Site
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Educational Resources
      url: /resources/
      weight: 3
    - name: Papers and projects
      url: /projects/
      weight: 4
    - name: GitHub
      url: https://github.com/Mexicajun1605
      weight: 5
    - name: Blog
      url: https://samlj.netlify.app/
      weight: 6
